# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-06 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Fibonacci',
        ),
    ]
